config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get  '/about',   to: 'static_pages#about'
  get  '/contact', to: 'static_pages#contact'
  get  '/signup', to: 'users#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get '/users/:id/profile', to: 'users#profile', as: 'profile'

  resources :users do
    resources :favorites, only: [:index]
  end
  resources :posts do
    resources :favorites, only: [:create, :destroy]
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  # 投稿を消した時に消せるようにするかは後で決める
  has_many :favorites, dependent: :destroy
  has_many :favorited_users, through: :favorites, source: :user, dependent: :destroy
  has_one_attached :image
  default_scope -> { order(created_at: :desc) }
  validates :user_id, presence: true
  validates :content, presence: true, length: { maximum: 1000 }
  validates :title, presence: true, length: {maximum: 20 }
  validates :price, presence: true, length: {maximum: 10 }
  validates :location, presence: true, length: {maximum: 20 }
  validates :image,   presence: true, content_type: { in: %w[image/jpeg image/gif image/png],
    message: "画像のフォーマットが正しくありません" },
    size:         { less_than: 5.megabytes,
    message: "画像のサイズは５MB以下でお願いします" }


  # ホーム画面用のサイズ
  def home_image
    image.variant(resize_to_limit: [160, 80])
  end

  # 詳細画面用のサイズ
  def display_image
    image.variant(resize_to_limit: [450, 300])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :logged_in_user, only: [:show, :new, :create, :destroy, :edit, :update]
  before_action :correct_user,   only: [:destroy, :edit, :update]

  def show
    @post = Post.find(params[:id])
    @favorite = Favorite.new
  end

  def new
    @post = current_user.posts.build if logged_in?
  end

  def create
    @post = current_user.posts.build(post_params)
    @post.image.attach(params[:post][:image])
    if @post.save
      redirect_to root_url
    else
      render 'new'
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      flash[:success] = "Placeを編集しました"
      redirect_to @post
    else
      render 'edit'
    end
  end

  def destroy
    @post.destroy
    redirect_to root_url
  end

  private

    def post_params
      params.require(:post).permit(:content, :title, :price, :location, :image)
    end

    def correct_user
      @post = current_user.posts.find_by(id: params[:id])
      redirect_to root_url if @post.nil?
    end

end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_post.html.erb
<div class="col-5 mb-5">
<%= link_to(post, class: '') do %>
    <div class="card h-20">
        <%= image_tag post.home_image, class: "rounded mx-auto d-block p-2" %>
        <div class="card-body p-2">
            <div class="text-center">
              <h5 class="fw-bolder"><%= truncate((post.title), length: 5) %></h5>
            </div>
            <div class="text-center m-1">
              <%= truncate((post.location), length: 4) %>
            </div>
            <div class="text-center m-1">
              <%= truncate(("#{post.price}円/日"), length: 12) %>
            </div>
            <div class="text-center m-2">
              <i class="fas fa-star"></i>
              <%= "#{post.favorited_users.count}"%>
            </div>
        </div>
    </div>
<% end %>
</div>

app/views/posts/edit.html.erb
<% provide(:title, 'Place編集') %>
<div class="row">
<div class="blank"></div>
<h1 class="display-5 fw-bolder">Placeを編集</h1>
<div class="borderbtm"></div>
<div class="blank"></div>
<div class="col-5 box">
<%= form_with(model: @post, local: true) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>

  <%= f.label :title, "タイトル"%>
　<%= f.text_field :title,placeholder: "20文字以内", class: 'form-control' %>

　<%= f.label :location, "所在地"%>
　<%= f.text_field :location,placeholder: "20文字以内", class: 'form-control' %>

　<%= f.label :price, "１日あたりの価格" %>
　<%= f.text_field :price,placeholder: "10ケタ以内", class: 'form-control' %>

 
  <%= f.label :content, "Placeの詳細"%>
  <div class="field">
    <%= f.text_area :content, placeholder: "Placeの詳細な情報を記入してください（1000文字以内）", class: "form-control",size: "50x10"%>
  </div>

  <span class="image">
    <%= f.file_field :image, accept: "image/jpeg,image/gif,image/png" %>
  </span>
  <div class="centerbtn">
  <%= f.submit "Post", class: "btn btn-outline-success" %>
  </div>
<% end %>
</div>
</div>

app/views/posts/index.html.erb
<header class="bg-dark py-5">
  <div class="container px-4 px-lg-5 my-5">
    <div class="text-center text-white">
      <h1 class="display-4 fw-bolder">Place</h1>
      <% if logged_in? %>
      <p class="lead fw-normal text-white-50 mb-0"></p>
      <% else %>
      <p class="lead fw-normal text-white-50 mb-0">サインインして場所を探す、あなたの場所を提供することができます</p>
      <%= link_to "アカウント作成", signup_path, class: "btn btn-lg btn-success" %>
      <% end %>
    </div>
  </div>
</header>
<% if @posts.any? %>
  <section class="py-5">
      <div class="container px-4 px-lg-5 mt-5">
          <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">
          <%= render @posts %>
          </div>
      </div>
  </section>
  <% else %>
  <h2 class="py-5 text-center">まだPlaceがありません</h2>
        <div class="blankbtm"></div>

  <% end %>

app/views/posts/new.html.erb
<% provide(:title, 'Place投稿') %>
<div class="row">
<div class="blank"></div>
<h1 class="display-5 fw-bolder">Placeを投稿</h1>
<div class="borderbtm"></div>
<div class="blank"></div>
<div class="col-5 box">
<%= form_with(model: @post, local: true) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>

  <%= f.label :title, "タイトル"%>
　<%= f.text_field :title,placeholder: "20文字以内", class: 'form-control' %>

　<%= f.label :location, "所在地"%>
　<%= f.text_field :location,placeholder: "20文字以内", class: 'form-control' %>

　<%= f.label :price, "１日あたりの価格" %>
　<%= f.text_field :price,placeholder: "10ケタ以内", class: 'form-control' %>

 
  <%= f.label :content, "Placeの詳細"%>
  <div class="field">
    <%= f.text_area :content, placeholder: "Placeの詳細な情報を記入してください（1000文字以内）", class: "form-control",size: "50x10"%>
  </div>

  <span class="image">
    <%= f.file_field :image, accept: "image/jpeg,image/gif,image/png" %>
  </span>
  <div class="centerbtn">
  <%= f.submit "Post", class: "btn btn-outline-success" %>
  </div>
<% end %>
</div>
</div>

app/views/posts/show.html.erb
<% provide(:title, @post.title) %>
<div class="row">

<div class="col-lg-6">
<div class="">
<h3 class="left"><%= @post.title %></h3>
<% if current_user.already_favorited?(@post) %>
 <div class="pt-3">
  <%= link_to "", post_favorite_path(@post), method: :delete, class: "fas fa-heart left" %>
  <p>「保存済み」</p>
 </div>
<% else %>
<div class="pt-3">
  <%= link_to "", post_favorites_path(@post), method: :post, class: "far fa-heart left" %>
  <p>「保存」</p>
  </div>
<% end %>
</div>
</div>

<div class="col-lg-6">
<%= link_to(@post.user, class: '') do %>
<p class="pt-3 left"><%= "ホスト:#{@post.user.name}" %></p>
<%= image_tag @post.user.mypage_image, class: "rounded-circle d-block pt-2" %>
<% end %>
</div>

<div class="border m-1"></div>
</div>

<div class="row">

<div class="col-lg-6">
<%= image_tag @post.display_image, class: "img-fluid rounded mx-auto d-block" %>
</div>

<div class="col-lg-6">
<div class="p-3">
<h5 class="p-3"><%= "・所在地:#{@post.location}" %></h5>
<h5 class="p-3"><%= "・価格:#{@post.price}円/日" %></h5>
</div>
</div>

</div>

<div class="row">
<div class="border m-1"></div>
</div>

<div class="row">
<div class="details">
<h3 class="text-center">ー  詳細情報  ー</h3>
</div>
<div class="border m-1"></div>
<p class="p-2"><%= @post.content %></p>
<div class="border m-1"></div>
<% if current_user?(@post.user) %>
<div class="centerbtn p-5">
<%= link_to "Placeを削除", @post, method: :delete, data: { confirm: "Placeを削除しますか?" }, class: "btn btn-outline-danger" %>
<%= link_to "Placeを編集", edit_post_path(@post), class: "btn btn-outline-success" %>
</div>
<% end %>
</div>