config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get  '/about',   to: 'static_pages#about'
  get  '/contact', to: 'static_pages#contact'
  get  '/signup', to: 'users#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get '/users/:id/profile', to: 'users#profile', as: 'profile'

  resources :users do
    resources :favorites, only: [:index]
  end
  resources :posts do
    resources :favorites, only: [:create, :destroy]
  end
end

app/views/layouts/_footer.html.erb
<footer class="py-5 bg-dark footer mt-auto">
  <div class="container"><p class="m-0 text-center text-white">株式会社民Park | 代表:高島成生</p></div>
  <div class="container">
  <nav class="navbar bg-dark">
  <div class="row">
    <%= link_to "お問い合わせ", contact_path, class: "navbar-brand text-white" %>
  </div>
</nav>
</div>
</footer>

app/views/layouts/_head.html.erb
<head>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  <!-- meta -->
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />        <meta name="description" content="株式会社民パークが始める新しいサービス、PlaceShip..." />
  <meta name="author" content="Naiki Takashima" />
  <title><%= full_title(yield(:title)) %></title>
  <!-- Favicon　未完成--> 
  <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
  <!-- Font Awesome -->
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.9.0/css/all.css">
  <!-- Core theme CSS (includes Bootstrap)-->
  <%# <link href="app/assets/stylesheets/styles.css" rel="stylesheet" /> %>
</head>

app/views/layouts/_header.html.erb
<!-- NavigationBar-->
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container px-4 px-lg-5">
                <%= link_to "Place", root_path, class: "navbar-brand" %>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0 ms-lg-4">
                        <li class="nav-item"><%= link_to "ホーム", root_path, class: "nav-link active" %></li>
                        <li class="nav-item"><%= link_to "Placeとは", about_path, class: "nav-link active" %></li>
                        <% if logged_in? %>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle active" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">マイページ</a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <li><%= link_to "MyPlace", current_user, class: "dropdown-item" %></li>
                                <li><hr class="dropdown-divider" /></li>
                                <li><%= link_to "お気に入りのPlace", user_favorites_path(current_user), class: "dropdown-item" %></li>
                                <li><hr class="dropdown-divider" /></li>
                                <li><%= link_to "マイページ編集", profile_path(current_user), class: "dropdown-item" %></li>
                                <li><hr class="dropdown-divider" /></li>
                                <li><%= link_to "ログイン情報更新", edit_user_path(current_user), class: "dropdown-item" %></li>
                                <li><hr class="dropdown-divider" /></li>
                                <li><%= link_to "ログアウト", logout_path, class: "dropdown-item", method: :delete %></li>
                            </ul>
                        </li>
                        <% else %>
                        <li class="nav-item"><%= link_to "ログイン", login_path, class: "nav-link active" %></li>
                        <% end %>
                    </ul>
                    <%= link_to "場所を提供する", new_post_path, class: "btn btn-outline-dark" %>
                </div>
            </div>
        </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <%= render 'layouts/head' %>
    <body data-turbolinks="false">
        <%= render 'layouts/header' %>
        <div class="container main">
        <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      　<% end %>
        <%= yield %>
        </div>
        <%= render 'layouts/footer' %>
    </body>
</html>